name: GitHub Actions Main CI

env:
  go-version: "1.20"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v5

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go-version }}

      - name: Build code
        run: go build -v ./...
