name: GitHub Actions solutions CI

env:
  go-version: "1.20"

on:
  push:
    branches:
      - challenge01-solutions
  pull_request:
    branches:
      - challenge01-solutions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.go-version }}

      - name: Build code
        run: go build -v ./...

  test:
    runs-on: ubuntu-latest 

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.go-version }}

      - name: Test code
        run: go test -v ./...
